{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-react-app.fullname" . }}
  labels:
    {{- include "my-react-app.labels" . | nindent 4 }}
{{- end }}
